### PR TITLE
feat: Deposit

### PR DESCRIPTION
**Pull request by Eknir**
Added a function to make a deposit by any party (called `stake`, as the function `deposit` already existed) . This may be used to create an additional layer of trust.

### CODE REVIEW

**Comment by AuHau** [comment]
Thanks a lot for the help with this Rinke!

Shouldn't there be also some way to get the stake back? For example when you terminate the offer?

**Comment by julianmrodri** [comment]
I think Providers should be able too withdraw this Stake at anytime. Also I would consider separating this into anothe Contract as we will have only instance the Provider will need to stake per service, and not for each different variation. 

For example if the `Provider` has 10 GB offered using Bee, and 10 GB offered using IPFS I think it should all be one Staking for that provider for the whole Storage module.

Decoupling  it into a "StakingContract" should be considered IMHO. What do you think?

**Comment by Eknir** [comment]
Hi guys,

Re: @AuHau 
> Shouldn't there be also some way to get the stake back? For example when you terminate the offer?

Definitely, we should allow people who send in money to withdraw it again. I think I was too ready for the weekend last Friday. I will add this. 
About getting a stake back when terminating an offer: the implementation of staking/unstaking was perhaps left to the bare minimal at the moment. Everybody can stake (even if you are not a provider). I would just leave it like this, until we give the staking some actual purpose (from the smart-contract level). Therefore, I would not recommend that you get your stake back when the offer is terminated (although the UX might ofc bridge this gap for the end-user to perceive that stake is retrieved when offer is terminated).

With regards to making a separate staking contract @julianmrodri . In principle, that could be a good idea, but the logic of staking/unstaking is so minimal at the moment that I don't see a reason to do this right now. If, in the future, we add some real functionality to staking it should be re-evaluated.

**Comment by vojtechsimetka** [comment]
Thanks @Eknir for sharing that reasoning, I would not write it better 😁 

@julianmrodri maybe you can share what is the upgrade mechanism for the RNS marketplace contracts?

**Comment by vojtechsimetka** [comment]
I think @julianmrodri and @AuHau you are right and this should just be completely separate locking contract that is shared across all the Marketplace services where it makes sense. It will make it very simple to review and audit and there is no lost functionality as for the storage contract the fact that money is locked is irrelevant at this stage.

**Comment by julianmrodri** [comment]
If we have a separate contract for Staking the idea in the Marketplace is to have it compatible with EIP 900, which is a nice and simple Standard: https://github.com/rsksmart/rif-marketplace-cache/pull/230
I saw a bunch of implementations one is Aragorn but there are some others.

**Comment by Eknir** [comment]
Ok, I'll make a separate contract. Closing this branch.

**Pull request closed without merging**
